
import logging
import httpx
from datetime import datetime, timezone
from typing import Optional, Dict, Any, Literal, Union

from v4.core.config import settings
from v4.core.database import SessionLocal, get_twitch_account

logger = logging.getLogger("v4.twitch.client")

class TwitchClient:
    """
    Twitch API Client wrapping Center Server API.
    Interacts with Center Server to manage Twitch subscription and fetch user data.
    """
    def __init__(self):
        self.base_url = settings.center_server_url.rstrip("/")
        self.api_key = settings.websub_client_api_key
        self.callback_base_url = settings.websub_callback_base_url.rstrip("/")

    def _get_headers(self) -> Dict[str, str]:
        return {
            "X-Client-Id": settings.websub_client_id,
            "X-Client-API-Key": self.api_key,
            "Content-Type": "application/json"
        }

    async def exchange_code_for_token(self, code: str) -> Optional[Dict[str, Any]]:
        """
        Exchange OAuth code for token via Center Server.
        GET /auth/twitch/token?code=...

        Note: The actual endpoint on Center Server might be different.
        Assuming a standard pattern or we fetch 'me' info which implies token exchange has happened
        or we send the code to a verify endpoint.

        Based on `auth_client.py`, the flow redirects to localhost with `code`.
        We need an endpoint on Center Server to "claim" this code or retrieve the session it established.

        However, usually:
        1. User goes to Center Server /auth/twitch/login
        2. Redirects to Twitch
        3. Redirects back to Center Server /auth/twitch/callback
        4. Center Server saves token and redirects to localhost with `code` (as a temporary auth code or session id).
        5. Localhost (Client) sends this `code` to Center Server to get the actual user info/token data.
        """
        url = f"{self.base_url}/api/twitch/me"
        # We might need to pass the code as a query param if it acts as a session claim ticket
        # Or, if the code is just for client-side confirmation, maybe we just query /me with our Client API Key
        # AND some identifier.

        # Design assumption: The 'code' returned to localhost is a temporary exchange token generated by Center Server.
        # So we send it to an endpoint to get the full account details.

        # For now, let's assume we call an endpoint to 'sync' or 'verify'
        # Or simply call public/private API if the Center Server already associated it with our Client ID.
        pass

    async def get_user_info(self, code: str) -> Optional[Dict[str, Any]]:
        """
        Exchange auth code for user info via Center Server.
        POST /api/twitch/auth/code-exchange
        """
        url = f"{self.base_url}/api/twitch/auth/code-exchange"

        # Center Server expects the redirect_uri that was used in the original auth request
        redirect_uri = f"{self.base_url}/auth/twitch/callback"

        payload = {
            "code": code,
            "redirect_uri": redirect_uri,
            "client_id": settings.websub_client_id
        }

        try:
            # Increase timeout to 30s as Center Server performs upstream calls to Twitch
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.post(url, headers=self._get_headers(), json=payload)

                if response.status_code == 200:
                    data = response.json()
                    # Response format: {"status": "ok", "username": "...", "user_id": "...", "events": [...]}
                    logger.info(f"Successfully retrieved Twitch user info: {data.get('username')}")
                    return data
                elif response.status_code == 401:
                    logger.error(
                        f"Twitch auth code exchange: Unauthorized (401). "
                        f"API key or client_id may be invalid. Response: {response.text[:200]}"
                    )
                    return None
                elif response.status_code == 404:
                    logger.error(
                        f"Twitch auth code exchange: Endpoint not found (404) at {url}. "
                        f"Check center_server_url in settings."
                    )
                    return None
                else:
                    logger.error(f"Failed to get Twitch user info: {response.status_code} - {response.text[:200]}")
                    return None
        except httpx.ConnectError as e:
            logger.error(
                f"Connection refused or DNS error reaching Center Server ({self.base_url}). "
                f"Check that center_server_url is correct and the server is running. Detail: {e}"
            )
            return None
        except httpx.TimeoutException as e:
            logger.error(
                f"Timeout waiting for Center Server response ({url}). "
                f"The server may be overloaded. Detail: {e}"
            )
            return None
        except httpx.HTTPStatusError as e:
            logger.error(f"HTTP error during Twitch user info fetch: {e}")
            return None
        except Exception as e:
            logger.exception(f"Unexpected error getting Twitch user info from {url}: {e}")
            return None

    async def disconnect_on_center(self, twitch_user_id: str) -> bool:
        """
        センターで Twitch 連携を解除（EventSub 削除・サーバー DB 削除）。
        失敗しても呼び出し側でローカル削除する場合があるため、通信エラー時は True を返すこともある。
        """
        if not settings.uses_center_server():
            logger.debug("Twitch disconnect_on_center skipped (poll mode)")
            return True
        url = f"{self.base_url}/api/twitch/auth/disconnect"
        tid = (twitch_user_id or "").strip()
        if not tid:
            return True
        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.post(
                    url,
                    headers=self._get_headers(),
                    params={"twitch_user_id": tid},
                )
            if response.status_code == 200:
                logger.info("センター側の Twitch 連携を解除しました。")
                return True
            logger.warning(
                "センター Twitch 連携解除: status=%s body=%s",
                response.status_code,
                getattr(response, "text", "")[:400],
            )
            return True
        except Exception as e:
            logger.warning("センター Twitch 連携解除リクエストに失敗しました（ローカル削除は続行可）: %s", e)
            return True

    async def register_eventsub(self) -> bool:
        """
        Request Center Server to subscribe to EventSub for the linked user.
        Same as ensure_eventsub(); kept for interface compatibility.
        """
        return await self.ensure_eventsub()

    async def ensure_eventsub(self) -> bool:
        """
        起動時用:
        1) 現在の EventSub 一覧を取得
        2) 必要イベント不足 or 期限切れ間近なら再購読を依頼
        3) 一覧取得不可なら従来の ensure-subscriptions にフォールバック
        """
        if not settings.uses_center_server():
            logger.debug("ensure_eventsub skipped (youtube_feed_mode=poll; center not used)")
            return True

        url = f"{self.base_url}/api/twitch/ensure-subscriptions"
        client_id = getattr(settings, "websub_client_id", "")
        if not client_id:
            logger.debug("No websub_client_id; skipping Twitch EventSub ensure.")
            return True

        client_callback_url = f"{settings.websub_callback_base_url.rstrip('/')}/webhook"
        payload = {
            "client_id": client_id,
            "callback_url": client_callback_url,
        }

        def _get_local_twitch_user_id() -> Optional[str]:
            db = SessionLocal()
            try:
                account = get_twitch_account(db)
                if account and getattr(account, "twitch_user_id", None):
                    return str(account.twitch_user_id)
                return None
            except Exception as e:
                logger.debug("Failed to load local twitch_user_id: %s", e)
                return None
            finally:
                db.close()

        def _parse_expiry_utc(sub: Dict[str, Any]) -> Optional[datetime]:
            for key in ("expires_at", "expiresAt", "session_expires_at"):
                v = sub.get(key)
                if isinstance(v, str) and v:
                    try:
                        dt = datetime.fromisoformat(v.replace("Z", "+00:00"))
                        if dt.tzinfo is None:
                            dt = dt.replace(tzinfo=timezone.utc)
                        return dt.astimezone(timezone.utc)
                    except Exception:
                        # v4-websub-server format: "YYYY/MM/DD HH:MM"
                        try:
                            dt = datetime.strptime(v, "%Y/%m/%d %H:%M")
                            return dt.replace(tzinfo=timezone.utc)
                        except Exception:
                            continue
            transport = sub.get("transport")
            if isinstance(transport, dict):
                v = transport.get("session_expires_at")
                if isinstance(v, str) and v:
                    try:
                        dt = datetime.fromisoformat(v.replace("Z", "+00:00"))
                        if dt.tzinfo is None:
                            dt = dt.replace(tzinfo=timezone.utc)
                        return dt.astimezone(timezone.utc)
                    except Exception:
                        pass
            return None

        def _extract_subscriptions(data: Dict[str, Any]) -> list[Dict[str, Any]]:
            if not isinstance(data, dict):
                return []
            for key in ("subscriptions", "items", "data", "events"):
                v = data.get(key)
                if isinstance(v, list):
                    return [x for x in v if isinstance(x, dict)]
            return []

        async def _get_current_subscriptions() -> Union[
            list[Dict[str, Any]], Literal["not_linked"], None
        ]:
            # 現行サーバー契約: query に twitch_user_id が必須（認証ヘッダー付きでセンター連携を検証）
            twitch_user_id = _get_local_twitch_user_id()
            if not twitch_user_id:
                logger.debug("No local twitch_user_id; skip subscription-list check.")
                return None

            list_url = f"{self.base_url}/api/twitch/subscriptions"
            try:
                async with httpx.AsyncClient(timeout=30.0) as c:
                    response = await c.get(
                        list_url,
                        headers=self._get_headers(),
                        params={"twitch_user_id": twitch_user_id},
                    )
                if response.status_code == 200:
                    data = response.json()
                    if isinstance(data, dict) and data.get("status") == "not_linked":
                        logger.info(
                            " Twitchアカウントが連携されていません。EventSubの購読はスキップします。"
                        )
                        return "not_linked"
                    subs = _extract_subscriptions(data)
                    logger.debug("Twitch EventSub current subscriptions fetched: %s", subs)
                    return subs
                if response.status_code == 404:
                    logger.info(
                        "Twitchアカウントが連携されていません。EventSubの購読はスキップします。"
                    )
                    return "not_linked"
                if response.status_code == 403:
                    logger.info(
                        "センターに登録されている Twitchアカウントと異なっています。"
                        " 再度Twitchアカウントの設定(再連携)を行ってください。"
                    )
                    return "not_linked"
                logger.debug(
                    "Twitch subscriptions API unavailable: %s status=%s body=%s",
                    list_url,
                    response.status_code,
                    getattr(response, "text", "")[:300],
                )
            except Exception as e:
                logger.debug("Twitch subscriptions API error (%s): %s", list_url, e)
            return None

        def _has_required_events(subs: list[Dict[str, Any]]) -> bool:
            types = set()
            for s in subs:
                t = s.get("type") or s.get("event_type")
                if isinstance(t, str):
                    types.add(t)
            # 最低限必要な3種
            return {"stream.online", "stream.offline", "channel.raid"}.issubset(types)

        def _needs_renewal(subs: list[Dict[str, Any]], threshold_sec: int = 86400) -> bool:
            now = datetime.now(timezone.utc)
            for s in subs:
                # callback_url は「クライアント Webhook 中継先」用の DB 列で、code-exchange 直後は
                # 未設定のままでも Twitch 側 EventSub は有効。空をもって再購読しない。

                # disabled系は再購読対象
                status = (s.get("status") or "").lower()
                if status and status not in (
                    "enabled",
                    "active",
                    "webhook_callback_verification_pending",
                ):
                    return True
                expiry = _parse_expiry_utc(s)
                if expiry:
                    remaining = (expiry - now).total_seconds()
                    if remaining < threshold_sec:
                        return True
            return False

        try:
            current_subs = await _get_current_subscriptions()
            if current_subs == "not_linked":
                return True
            if current_subs is not None:
                if current_subs and _has_required_events(current_subs) and not _needs_renewal(current_subs):
                    logger.info("Twitch EventSub の現在購読は正常です（再購読不要）。")
                    return True
                logger.info("Twitch EventSub は再購読が必要です。再購読を実行します。")

            async with httpx.AsyncClient(timeout=30.0) as c:
                response = await c.post(
                    url,
                    headers=self._get_headers(),
                    json=payload,
                )
            if response.status_code == 200:
                data = response.json() if response.content else {}
                st = data.get("status") if isinstance(data, dict) else None
                if st == "not_linked":
                    logger.info(
                        "Twitchアカウントが連携されていません。 処理をスキップします。"
                        " 設定からTwitchアカウントの設定(再連携)をお願いします。"
                    )
                    return True
                if st == "disabled":
                    logger.debug("Twitch EventSub ensure skipped (disabled on center server).")
                    return True
                if st == "ok":
                    # 成功は日本語で概要1行（詳細はDEBUG）
                    logger.info("Twitch EventSub の再購読に成功しました。")
                    logger.debug("Twitch ensure-subscriptions events: %s", data.get("events"))
                    return True
                logger.error("Twitch EventSub の再購読に失敗しました。")
                logger.debug("Twitch ensure-subscriptions unexpected payload: %s", data)
                return False
            if response.status_code == 404:
                logger.info(
                        "Twitchアカウントが連携されていません。 処理をスキップします。"
                        " 設定からTwitchアカウントの設定(再連携)をお願いします。"
                )
                return True
            if response.status_code == 401:
                logger.error("Twitch EventSub の再購読に失敗しました（APIキーが無効です）。")
                logger.debug(
                    "Twitch ensure-subscriptions 401 response: %s",
                    getattr(response, "text", ""),
                )
                return False
            logger.error("Twitch EventSub の再購読に失敗しました。")
            logger.debug(
                "Twitch ensure-subscriptions failed status=%s body=%s",
                response.status_code,
                getattr(response, "text", ""),
            )
            return False
        except Exception as e:
            logger.error("Twitch EventSub の再購読に失敗しました。")
            logger.debug("Twitch ensure-subscriptions exception: %s", e, exc_info=True)
            return False

    async def get_stream_info(self, user_id: str) -> Optional[Dict[str, Any]]:
        """
        Fetch current stream info for a user.
        GET /api/twitch/streams?user_id=...
        """
        url = f"{self.base_url}/api/twitch/streams"
        params = {"user_id": user_id}

        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                response = await client.get(url, headers=self._get_headers(), params=params)
                if response.status_code == 200:
                    data = response.json()
                    # Center Server API should return a list of streams or single object
                    # Assuming standard Twitch API structure wrapped: { "data": [...] } or list directly
                    streams = data.get("data", [])
                    if streams:
                        return streams[0]
                    return None
                else:
                    logger.error(f"Failed to get stream info: {response.status_code}")
                    return None
        except httpx.ConnectError as e:
            logger.error(f"Connection error getting stream info from {url}: {e}")
            return None
        except httpx.TimeoutException as e:
            logger.error(f"Timeout getting stream info from {url}: {e}")
            return None
        except Exception as e:
            logger.error(f"Unexpected error getting stream info: {e}")
            return None
